### ISSUE TITLE
Generate Slack manifest automatically?

### ISSUE THREAD

**Issue by Nexyro** [ManoManoTech/firefighter-incident#69]
Creating a Slack bot is a tiresome task, especially when it comes to defining permissions. This would be easier with an app manifest.

Is it possible to export it and put it somewhere on the repo?

**Comment by GabDug** [comment]
Hello @Nexyro!

Yes, it should be possible to generate the manifest with a CLI command. 

Please refer to [this documentation](https://manomanotech.github.io/firefighter-incident/latest/contributing/0002-setup-slack-app/#create-your-own-slack-app-and-install-it-to-your-workspace), and let me know if there is anything wrong with the docs or the CLI usage.

Have a great day!

**Comment by Nexyro** [comment]
Perfect, sorry not reading enough the doc :grin:
